// npm run notices            → regenerate THIRD_PARTY_NOTICES.md from package-lock.json
// npm run notices -- --check → exit 1 if the committed file is out of date

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

interface LockPackage {
  version?: string;
  license?: string;
  dev?: boolean;
  optional?: boolean;
}

const root = join(import.meta.dirname, '..');
const outFile = join(root, 'THIRD_PARTY_NOTICES.md');
const lock = JSON.parse(readFileSync(join(root, 'package-lock.json'), 'utf8')) as {
  packages: Record<string, LockPackage>;
};
const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')) as {
  devDependencies?: Record<string, string>;
};

const nameOf = (path: string): string => path.slice(path.lastIndexOf('node_modules/') + 13);

function rows(entries: [string, LockPackage][]): string[] {
  const seen = new Map<string, { name: string; version: string; license: string }>();
  for (const [path, p] of entries) {
    const name = nameOf(path);
    const version = p.version ?? '';
    seen.set(`${name}@${version}`, { name, version, license: p.license ?? 'UNKNOWN' });
  }
  return [...seen.values()]
    .sort((a, b) => a.name.localeCompare(b.name) || a.version.localeCompare(b.version))
    .map(
      (p) =>
        `| [${p.name}](https://www.npmjs.com/package/${p.name}) | ${p.version} | ${p.license} |`,
    );
}

const all = Object.entries(lock.packages).filter(([path]) => path.startsWith('node_modules/'));
const runtime = all.filter(([, p]) => !p.dev);
const directDev = new Set(Object.keys(pkg.devDependencies ?? {}));
const tools = all.filter(([path, p]) => p.dev && directDev.has(nameOf(path)));

const unknown = runtime.filter(([, p]) => !p.license).map(([path]) => nameOf(path));
if (unknown.length > 0) {
  console.error(`notices: runtime packages without a license field: ${unknown.join(', ')}`);
  process.exit(1);
}

const table = ['| Package | Version | License |', '|---|---|---|'];
const content = [
  '# Third-Party Notices',
  '',
  '<!-- Generated by `npm run notices` from package-lock.json. Do not edit by hand. -->',
  '',
  'This project is licensed under the GNU General Public License v3 (see [LICENSE](LICENSE)).',
  'It bundles or uses the third-party packages below, each under its own license.',
  'The full license text of each package ships in its npm package.',
  '',
  '## Bundled in the web app',
  '',
  'These packages (and their dependencies) are included in the published site.',
  '',
  ...table,
  ...rows(runtime),
  '',
  '## Development tools (not distributed)',
  '',
  'Direct development dependencies used to build and test the project. They are not part of the published site.',
  '',
  ...table,
  ...rows(tools),
  '',
].join('\n');

if (process.argv.includes('--check')) {
  if (!existsSync(outFile) || readFileSync(outFile, 'utf8') !== content) {
    console.error('notices --check: THIRD_PARTY_NOTICES.md is out of date. Run `npm run notices`.');
    process.exit(1);
  }
  console.log('notices --check: THIRD_PARTY_NOTICES.md is up to date.');
} else {
  writeFileSync(outFile, content);
  console.log(`notices: wrote THIRD_PARTY_NOTICES.md (${runtime.length} runtime packages).`);
}
